name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup venv
      run: |
        python3 -m venv /tmp/venv_vali
        
    - name: Build and Install Package
      run: | 
        git submodule update --init --recursive
        source /tmp/venv_vali/bin/activate
        python3 -mpip install pydantic
        python3 -mpip install . --verbose
        python3 -mpip install src/PytorchNvCodec --verbose

    - name: Run Tests
      run: |
        source /tmp/venv_vali/bin/activate
        cd tests
        python3 ./test_PyFFmpegDecoder.py || true
        python3 ./test_PyFfmpegDemuxer.py || true
        python3 ./test_PyNvDecoder.py     || true
        python3 ./test_PyNvEncoder.py     || true
        python3 ./test_PySurface.py       || true

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: tests/*.yuv
        retention-days: 1
