name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup venv
      run: |
        python3 -m venv /tmp/venv_vali
        
    - name: Build and Install Package
      run: | 
        git submodule update --init --recursive
        source /tmp/venv_vali/bin/activate
        python3 -mpip install pydantic
        python3 -mpip install . --verbose
        python3 -mpip install src/PytorchNvCodec --verbose

    - name: Run Tests
      run: |
        source /tmp/venv_vali/bin/activate
        python3 -munittest discover tests